default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: rubyuser
  password: password1

development:
  <<: *default
  database: rpg_development

test:
  <<: *default
  database: rpg_test

production:
  <<: *default
  database: rpg_production
